//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _31_NgoMinhThuan_THBuoi11.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ChiTiet
    {
        public int MaHD { get; set; }
        public int MaSP { get; set; }
        public Nullable<int> SoLuong { get; set; }
    
        public virtual tbl_HoaDon tbl_HoaDon { get; set; }
        public virtual tbl_SanPham tbl_SanPham { get; set; }
        public virtual tbl_SanPham tbl_SanPham1 { get; set; }
    }
}
